### ISSUE TITLE
Name the event/configuration model and syntax

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/nereon-models#7]
We need a project name for:
* the configuration model (unified configuration)
  * unifies command line flags, environment variables, configuration files;
  * a central configuration model that allows unified configuration management, to represent every configurable element (a software, an os, a device) (like SNMP), but allow dynamically changing the configuration (e.g., `computer.software.nginx.find(host: 'myhost.com').port.set(8080)`)
* the event model (unified logging)
* a syntax for configuration (realization of the configuration model, as in Go: https://github.com/riboseinc/go-multiconfig; C: https://github.com/riboseinc/libmulticonfig)

**Comment by opoudjis** [comment]
henoconfig, henoconf

uniconf
omniconf
dynaconf

(all of which are taken)

So uni-, heno-, omni-, dyna- are all possible prefixes to the following:

keryx, ceryx: "herald"
rheda: "light carriage used in the Roman courier mail service"
-mand: "command"
-tagos: "commander"
-keleu: "command" (-keleust, -keleum)

My best of breed at the moment is omnimand.

**Comment by ronaldtse** [comment]
I have a problem reading "omnimand" 😉 No "allenos"?

**Comment by opoudjis** [comment]
Hidden

**Comment by opoudjis** [comment]
(And please close the ticket.)

**Comment by opoudjis** [comment]
Nereon:

https://en.wikipedia.org/wiki/Nereus, the original Greek god of the sea, was renowned as someone trustworthy, and a prophet—and as a shapeshifter. Like the sea itself, Nereus constantly changed his form.

Just like the different forms that we take to get a computer to carry out a task.
 
Nēreōn is Greek for the place where Nereus is. It could be his temple. It could be his lair. It's where the shapeshifting takes place. It's the config file where all the various shapes of a command are brought together.

It's where the various events of various shape get logged as well. They get logged, of course, in a Nerelog. (A _Nereolog_, strictly speaking, but that's the thing with changing shapes: you can't be too strict about it.) A Nerelog in Greek would be a a student of Nereus: a _nēreológos_. Or else, if you shift the accent as well as your shape, you become a _nēreólogos_: a collection of Nereuses. A cata-log (yes, it's the same suffix) of all the forms that Nereus has taken, all the events in their shape-shifting glory.

**Comment by ronaldtse** [comment]
An excellent story worth reading by itself.

**Comment by opoudjis** [comment]
@ronaldtse  Please close ticket.
