### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [riboseinc/nereon-models#8]
Convert Nereon Event and Configuration StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.

- [PNG.zip](https://github.com/riboseinc/nereon-models/files/2336205/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/nereon-models/files/2336206/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/nereon-models/files/2336207/SVG.zip)

**Comment by ronaldtse** [comment]
Completed in 2dacbe70509f4ce07a6d56ca2159b59f24aeb156. Thanks @VasBu !

ping: @drystone

**Comment by drystone** [comment]
Agreed - very nice. Handy tool, PlantUML! Thanks @VasBu
